### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by RodrigoA-Fernandez** [esm7/obsidian-vimrc-support#203]
**Please Review Before Posting!**

- [x] I checked that the bug *does not happen* in the [CodeMirror Vim demo](https://codemirror-vim--util.repl.co/). If it does, please report it [there](https://github.com/replit/codemirror-vim) and not here.
- [x] I'm reasonably sure that this bug is indeed about the Vimrc file support and not a general Vim in Obsidian issue. If it's a general Vim issue, report it [here](https://forum.obsidian.md/c/bug-reports/7).

**Describe the bug:**

Status bar is not like the ReadMe example even when I've used the same css.

**To Reproduce:**

- Install the plugin 
- add css 
- turn on status bar options in settings 
- restart obsidian.

**Environment (please complete the following information):**

 - OS: Windows
 - Vimrc plugin version: 0.9.0

**Additional context:**

![imagen_2023-10-07_220829733](https://github.com/esm7/obsidian-vimrc-support/assets/126868582/823de886-0cbb-4072-8ac6-c0025b608e92)

**Comment by stracaganasse** [comment]
I was testing the css snippet myselft and here is what I understood.

the css is looking for an attribute `[data-vim-mode="normal"]` in order to change the color, background etc.

while debugging inside the app and looking at the plugin `main.js` I found a couple of issues:

- the class that is given to the statusbar element seems to differ from the `vimrc-support-vim-mode`, i could only find the `plugin-obsidian-vimrc-support` one. This would hint at a former class that is no longer set by the plugin.
- the script now uses the `.setText(this.currentVimStatus)` method to change the shown text, which as of now is the colored emoji circle, but does not use any `.setAttribute()` to add the `data-vim-mode="<normal|insert|visual>"` attribute.

All things considered the css snippet is surely based on an old version of the plugin. I managed to hack the script a little to validate my suspicions -got the text change working or the attribute set- but i have zero experience with obsidian and CodeMirror APIs so I don't trust what i wrote for now.

**Comment by shsw228** [comment]
I'm leaving a simple CSS patch here for newcomers.

- I'm not a web frontend engineer, so there may be some mistakes.
- `Vim chord display`  is disabled. I couldn't think of a good solution for this at the moment.
- Tested on v1.8.10.


<img width="903" alt="Image" src="https://github.com/user-attachments/assets/bd0ab449-fbea-4de0-8bbf-9eb1aaa22a9f" />

```css
div.status-bar {
  width: 100vw !important;
  justify-content: flex-start !important;
  padding-left: 0 !important; 
  padding-right: 0 !important; 
}
div.status-bar-item.plugin-obsidian-vimrc-support {
  /* Papercolor theme */
  --text-color-normal: #585858;
  --text-color-insert: #005f87;
  --text-color-visual: white;
  --text-color-replace: white;

  --background-color-normal: #eeeeee;
  --background-color-insert: #eeeeee;
  --background-color-visual: #d75f00;
  --background-color-replace: #d70087;
}

div.status-bar-item.plugin-obsidian-vimrc-support {
  /* 
    Move to bottom left corner and discard top/left/bottom space
    from container paddings.
   */
  order: -9999; 
  margin: -4px auto -5px -5px;
  /* 
    We have the :after pseudo-element next, so padding-right
    is not needed
    */
  padding-right: 0px;
  padding-left: 1em;

  /* Use Monospace font */
  font-family: 'Noto Mono for Powerline'; /* !!! Needs to be a powerline font */
  font-weight: bold;
  font-size: 1.2em;

  /* Clear spaces made from radius borders */
  border-top-right-radius: 0px;
  border-bottom-right-radius: 0px;
}

div.status-bar-item.plugin-obsidian-vimrc-support:after {
  /* Powerline separator character */
  content: '';
  position: relative;
  font-size: 1.5rem;
  left: 0.9rem;

  /* Fine adjust the position */
  margin-top: 0.1rem;
}

/* Normal */
div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="normal"]:after {
  color: var(--background-color-normal);
}
div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="normal"] {
  color: var(--text-color-normal);
  background-color: var(--background-color-normal);
}

/* Insert */
div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="insert"]:after {
  color: var(--background-color-insert);
}
div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="insert"] {
  color: var(--text-color-insert);
  background-color: var(--background-color-insert);
}

/* Visual */
div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="visual"]:after {
  color: var(--background-color-visual);
}
div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="visual"] {
  color: var(--text-color-visual);
  background-color: var(--background-color-visual);
}

/* Replace */
div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="replace"]:after {
  color: var(--background-color-replace);
}
div.status-bar-item.vimrc-support-vim-mode[data-vim-mode="replace"] {
  color: var(--text-color-replace);
  background-color: var(--background-color-replace);
}

```
